/** Research table backing functional_age_v1. Every coefficient in methodology.js should trace here. */

export const RESEARCH_TABLE = [
  {
    metric: 'sleep_duration',
    paper: 'Itani O et al. Sleep Med. 2017',
    doi: '10.1016/j.sleep.2016.08.006',
    pmid: '27743803',
    population: 'Pooled prospective cohorts',
    sampleSize: 5172710,
    ageRange: 'adult, mixed',
    sexStratification: 'not primary',
    referenceGroup: 'normal sleepers vs short sleepers',
    measurementDefinition: 'mostly self-reported sleep duration',
    hazardRatio: 1.12,
    confidenceInterval: '1.08–1.16',
    doseResponseShape: 'linear increase in mortality below 6 hours',
    adjustments: 'study-specific; meta-analysis of adjusted RRs',
    wearableApplicability: 'self-report overestimates sleep vs wearable; Saint-Maurice 2024 shows stronger objective short-sleep HRs',
    limitations: 'heterogeneous short-sleep cutoffs; reverse causality for long sleep',
    usedAs: 'short-sleep HR anchor; WHOOP overrides long-sleep penalty',
  },
  {
    metric: 'sleep_consistency',
    paper: 'Windred DP et al. Sleep. 2024',
    doi: '10.1093/sleep/zsad253',
    pmid: '37738616',
    population: 'UK Biobank accelerometer subsample',
    sampleSize: 60977,
    ageRange: '62.8 ± 7.8 years',
    sexStratification: '55% female; models adjusted for sex',
    referenceGroup: 'SRI 0–20th percentile (SRI < 71.6)',
    measurementDefinition: 'Sleep Regularity Index from ~7 days actigraphy',
    hazardRatio: 0.7,
    confidenceInterval: '0.59–0.83 fully adjusted, Q5 vs Q1',
    doseResponseShape: 'monotonic; higher SRI → lower ACM',
    adjustments: 'age, sex, ethnicity, sociodemographic, lifestyle, health; duration in nested models',
    wearableApplicability: 'WHOOP Consistency is similar but uses a 5-day baseline and scores slightly lower than SRI',
    limitations: 'older, mostly white UK cohort; 1 week snapshot; correlational',
    usedAs: 're-anchored so 70% Consistency = HR 1.0 (WHOOP referent), not Windred Q1',
  },
  {
    metric: 'steps',
    paper: 'Paluch AE et al. Lancet Public Health. 2022',
    doi: '10.1016/S2468-2667(21)00302-9',
    pmid: '35247352',
    population: '15 international cohorts',
    sampleSize: 47471,
    ageRange: 'mean 65.0; analyzed <60 vs ≥60',
    sexStratification: '68% female; sex interaction NS',
    referenceGroup: 'quartile 1 (~3553 steps/day)',
    measurementDefinition: 'device-measured daily steps',
    hazardRatio: 'Q2 0.60, Q3 0.55, Q4 0.47 vs Q1',
    confidenceInterval: 'see paper',
    doseResponseShape: 'nonlinear spline; plateau 8–10k (<60y), 6–8k (≥60y)',
    adjustments: 'study-level Cox, inverse-variance random effects',
    wearableApplicability: 'high — device steps',
    limitations: 'Q1 referent is sedentary, not health-optimized; we re-anchor HR(target)=1',
    usedAs: 'age-dependent target and relative dose-response shape',
  },
  {
    metric: 'steps',
    paper: 'Stens NA et al. JACC. 2023',
    doi: '10.1016/j.jacc.2023.07.029',
    pmid: '37676198',
    population: '12 studies, general population',
    sampleSize: 111309,
    ageRange: 'adult mixed',
    sexStratification: 'sex did not modify dose-response',
    referenceGroup: '2000 steps/day',
    measurementDefinition: 'objectively measured step counts',
    hazardRatio: '0.40 at ~8763 steps vs 2000 for ACM',
    confidenceInterval: '0.38–0.43 at optimal dose',
    doseResponseShape: 'nonlinear; significant from ~2600; optimal ~8763',
    adjustments: 'study-specific then pooled',
    wearableApplicability: 'high',
    limitations: '2000-step referent is not WHOOP’s 8000-step healthy referent',
    usedAs: 'confirms plateau near 8–9k and steep low-end slope',
  },
  {
    metric: 'moderate_activity',
    paper: 'Lee DH et al. Circulation. 2022',
    doi: '10.1161/CIRCULATIONAHA.121.058162',
    pmid: '35876019',
    population: 'NHS + HPFS US adults',
    sampleSize: 116221,
    ageRange: 'adult, long follow-up',
    sexStratification: 'both sexes (two sex-specific cohorts)',
    referenceGroup: 'no long-term leisure MPA/VPA',
    measurementDefinition: 'repeated self-report leisure-time PA',
    hazardRatio: '~0.75–0.81 meeting guidelines vs none',
    confidenceInterval: 'VPA 75–149 min/wk ACM 0.81 (0.76–0.87)',
    doseResponseShape: 'near-max at 300–600 min MPA or 150–300 min VPA; no clear harm above',
    adjustments: 'mutually adjusted MPA and VPA',
    wearableApplicability: 'WHOOP uses logged HRR zone time as a proxy for guideline minutes',
    limitations: 'self-report; not HRR zones',
    usedAs: 'moderate-activity saturating curve and “benefits continue past the target”',
  },
  {
    metric: 'moderate_activity',
    paper: 'Martinez-Gomez D et al. JAMA Netw Open. 2024',
    doi: '10.1001/jamanetworkopen.2024.46802',
    pmid: '39570587',
    population: '4 multinational megacohorts',
    sampleSize: 'very large (megacohorts)',
    ageRange: 'stratified by age',
    sexStratification: 'adjusted',
    referenceGroup: 'lowest activity',
    measurementDefinition: 'cohort-specific PA',
    hazardRatio: 'age-varying; stronger inverse association at older ages',
    confidenceInterval: 'see paper',
    doseResponseShape: 'inverse, age-modified',
    adjustments: 'cohort models',
    wearableApplicability: 'supports WHOOP lowering zone-time targets with age',
    limitations: 'not wearable HRR',
    usedAs: 'age slope on zone 1–3 / 4–5 targets',
  },
  {
    metric: 'vigorous_activity',
    paper: 'Ahmadi MN et al. Eur Heart J. 2022',
    doi: '10.1093/eurheartj/ehac572',
    pmid: '36302460',
    population: 'UK Biobank wrist accelerometry',
    sampleSize: 71893,
    ageRange: 'median 62.5',
    sexStratification: '55.9% female',
    referenceGroup: '~2.2 min/week VPA (5th percentile)',
    measurementDefinition: 'accelerometer VPA volume',
    hazardRatio: '0.64 at ~54 min/week; ~0.82 at ~15 min/week vs reference',
    confidenceInterval: 'optimal 0.54–0.77',
    doseResponseShape: 'steep then diminishing; CVD mortality more linear',
    adjustments: 'demographic and lifestyle',
    wearableApplicability: 'short vigorous bouts — conceptually close to Z4–Z5',
    limitations: 'older sample; VPA ≠ HRR Z4–Z5 exactly',
    usedAs: 'vigorous saturating curve (10 min target, ~55 min near-optimal)',
  },
  {
    metric: 'strength',
    paper: 'Momma H et al. Br J Sports Med. 2022',
    doi: '10.1136/bjsports-2021-105061',
    pmid: '35228201',
    population: '16 prospective cohorts',
    sampleSize: 'pooled adult cohorts',
    ageRange: '≥18',
    sexStratification: 'mixed',
    referenceGroup: 'no muscle-strengthening activity',
    measurementDefinition: 'self-reported muscle-strengthening minutes',
    hazardRatio: '0.83–0.90 ACM at 30–60 min/week (10–17% lower)',
    confidenceInterval: 'see paper',
    doseResponseShape: 'J-shaped; max 30–60 min; unclear / attenuated above',
    adjustments: 'independent of aerobic activity',
    wearableApplicability: 'WHOOP uses logged strength-class sports, not 1RM',
    limitations: 'self-report; J-shape poorly understood — WHOOP withholds extra benefit >2h rather than penalizing',
    usedAs: 'zero/target/best/plateau knots at 0 / 40 / 60 / 120 min',
  },
  {
    metric: 'strength',
    paper: 'Shailendra P et al. Am J Prev Med. 2022',
    doi: '10.1016/j.amepre.2022.03.020',
    pmid: '35597661',
    population: 'prospective cohorts of resistance training',
    sampleSize: 'pooled adult cohorts',
    ageRange: 'adult',
    sexStratification: 'mixed',
    referenceGroup: 'no resistance training',
    measurementDefinition: 'self-reported resistance training participation / volume',
    hazardRatio: 'inverse association with ACM and CVD mortality',
    confidenceInterval: 'see paper',
    doseResponseShape: 'benefit at moderate weekly volume; little extra at high volume',
    adjustments: 'study-specific',
    wearableApplicability: 'supports logged strength minutes, not load or 1RM',
    limitations: 'self-report; heterogeneous exposure definitions',
    usedAs: 'confirms saturating strength-volume curve used with Momma 2022',
  },
  {
    metric: 'vo2_max',
    paper: 'Mandsager K et al. JAMA Netw Open. 2018',
    doi: '10.1001/jamanetworkopen.2018.3605',
    pmid: '30646252',
    population: 'Cleveland Clinic referral treadmill tests',
    sampleSize: 122007,
    ageRange: '53.4 ± 12.6',
    sexStratification: '59.2% male; age-sex percentiles',
    referenceGroup: 'low fitness (<25th percentile age-sex)',
    measurementDefinition: 'peak estimated METs on treadmill',
    hazardRatio: 'elite vs low 0.20; low vs elite 5.04',
    confidenceInterval: 'elite vs low 0.16–0.24',
    doseResponseShape: 'inverse, no observed upper limit in this cohort',
    adjustments: 'clinical risk factors',
    wearableApplicability: 'wearable VO2 is estimated, not treadmill METs — labeled if not measured',
    limitations: 'referral population; 13%/MET is the WHOOP-cited rule of thumb, not this paper’s primary estimand',
    usedAs: '13%/MET continuous slope with ΔMET clamp; WHOOP age-sex table as referent',
  },
  {
    metric: 'rhr',
    paper: 'Zhang D et al. CMAJ. 2016',
    doi: '10.1503/cmaj.150535',
    pmid: '26598376',
    population: 'general population cohorts',
    sampleSize: 1246203,
    ageRange: 'adult mixed',
    sexStratification: 'mixed',
    referenceGroup: 'lowest RHR category / per 10 bpm',
    measurementDefinition: 'mostly daytime clinic RHR (WHOOP uses sleep RHR)',
    hazardRatio: 1.09,
    confidenceInterval: '1.07–1.12 per +10 bpm ACM',
    doseResponseShape: 'linear ACM from ~45 bpm; >80 bpm RR 1.45 vs lowest',
    adjustments: 'traditional CVD risk factors in subset',
    wearableApplicability: 'sleep RHR is typically lower than clinic RHR; WHOOP chose 60/64 as sleep-based referents',
    limitations: 'heterogeneity, publication bias noted by authors',
    usedAs: '1.09 per 10 bpm around WHOOP sex-specific referents',
  },
  {
    metric: 'lean_body_mass',
    paper: 'Jayedi A et al. Int J Obes. 2022',
    doi: '10.1038/s41366-022-01165-5',
    pmid: '35717418',
    population: '35 prospective cohorts',
    sampleSize: 923295,
    ageRange: 'adults; weaker/null in >60y for BF%',
    sexStratification: 'mixed',
    referenceGroup: 'per 10% BF increment; J-shape nadir ~25% BF',
    measurementDefinition: 'body fat % / fat mass / FMI / VAT',
    hazardRatio: 1.11,
    confidenceInterval: '1.02–1.20 per 10% BF in general adults',
    doseResponseShape: 'J-shaped BF% and fat mass',
    adjustments: 'heterogeneous; reverse causation concerns',
    wearableApplicability: 'home BIA LBM% is noisy vs DXA; optional input',
    limitations: 'J-shape vs WHOOP “higher LBM is better” — we apply modest surplus benefit only',
    usedAs: '10% LBM deficit ≈ 10% BF surplus → HR 1.11',
  },
  {
    metric: 'effective_age',
    paper: 'Spiegelhalter D. BMC Med Inform Decis Mak. 2016',
    doi: '10.1186/s12911-016-0342-z',
    pmid: '27496343',
    population: 'methodological',
    sampleSize: null,
    ageRange: 'adult',
    sexStratification: 'n/a',
    referenceGroup: 'referent risk profile',
    measurementDefinition: 'effective age from hazard ratio and aging hazard',
    hazardRatio: 'e^{c t} = HR with c ≈ 0.1 / year',
    confidenceInterval: 'n/a',
    doseResponseShape: 'log-linear Gompertz',
    adjustments: 'assumes proportional hazards across age',
    wearableApplicability: 'framework only',
    limitations: 'effective age ≠ remaining life expectancy (Pang & Hanley 2021)',
    usedAs: 'AgeImpact = ln(HR) / 0.1',
  },
];
